### ISSUE TITLE
Lowpass filter / Very aggressive noise reduction on camera audio.

### ISSUE THREAD

**Issue by divid3byzer0** [M1cha/android_device_xiaomi_aries#16]
The audio recorded by the video camera is muffled and of low quality. MIUI Rom used to have the same audio problem but they fixed in recent versions of MIUI v5 but I don't know if the issue is a kernel one or some config file edit.

Probably it's a low priority issue but just writing this to be fixed eventually.

**Comment by ghost** [comment]
AFAIK in MIUI the camera is actually using the main microphone for recording. The problem with noise reduction was "resolved" by allowing the user to turn the noise reduction off completely (at least for phone calls, though I assume it applies system wide). IMHO there is no such on/off setting in CM 10.2. Partial workaround is to cover the back microphone with sticky tape.

**Comment by M1cha** [comment]
so u have this problem in MIUI, too but only with noise reduction enabled(default)?

**Comment by ghost** [comment]
Yes, the problem existed also on MIUI and was worse with NR enabled and better with NR disabled. But even with the latter, the quality was fairly poor - if I recall correctly, only the cameraman's voice was clearly recorded, anything else (i.e. especially the shooted scene) sounded like a voice in the metalic pipe.

This video on youtube resembles what I usually had:
http://www.youtube.com/watch?v=wCU_toKHL9Q

This one sounds unbelievable good to me and unfortunatelly I never get something similarly sounding:
http://www.youtube.com/watch?v=n1FVasCWYSs

I would not be surprised if different users had different sound quality in recordings...

I will try to test with recent version of MIUI, however the test will not be the same since I have the back microphone covered with a tape, which is further under the protective back cover - which cannot be removed without its destroying...

**Comment by divid3byzer0** [comment]
I cannot pinpoint the exact ROM version in which Xiaomi fixed the camera sound in MIUI, but I think that it was at the same time they created the option Noise Supression in Sound Settings. But I don't think it has to do with the video sound recording, just calls. Actually I can't even disable NR, just choose between Single Mic NR or Dual Mic NR.

I really have no idea why it sounds different in the MIUI / WIUI roms but the difference is noticeable once I change to any other ROM not based on MIUI, and it's one of the things keeping me from changing, since I record some videos with music content (parties) and I can only get decent sound with the MIUI / WIUI roms. All other roms (coface's, ivan's, M1cha's) give me very poor audio recording that equals the sound MIUI had before they fixed it.

By the way, I have a MI2 16gb.

**Comment by M1cha** [comment]
As far as I know MIUI never added the option and this is a miuiandroid feature or am I wrong?

**Comment by ghost** [comment]
I have to confirm that MIUI really improved the quality of sound recording. Now I tested with the last version and no more troubles as I referenced in my comment yesterday evening. The current settings in sound options (NR options have changed, too, as reported by divd3byzer0: Single Mic or Dual Mic) refer clearly to "Phone calls" and do not seem to affect video recordings.

EDIT: I flashed MIUI 3.11.29 from Xiaomi and can confirm the settings for NR are the same as in MIUI from miuiandroid.com.

**Comment by M1cha** [comment]
pls check if it's working in this experimental build:
http://d-h.st/BAL

**Comment by ghost** [comment]
For me, the sound in video recording is much better.
