### ISSUE TITLE
Headphone don't work when I make a call.

### ISSUE THREAD

**Issue by snoodlupa** [M1cha/android_device_xiaomi_aries#6]
I can't heard any noise from other part, but If I remove the headphone, all work.

**Comment by ghost** [comment]
Same here.

I tried both with standard stereo headphones (no microphone, no buttons) and some other with mic+single button. The other party does not hear anything at all, too. Neither is anything recorded on my phone (ACR recorder).

When choosing "loud speaker" in Phone app during the call (while headphones are still plugged in), it is possible to continue in the call.

**Comment by M1cha** [comment]
does it work with ivans rom? if so it is a software problem which I can easily fix.

**Comment by ghost** [comment]
Where do I find "ivan's" rom? Do you mean the source code in this thread:
http://xiaomi.eu/community/threads/android-4-3-for-mi2-2s-2a-open-source.22539/
Unfortunately, the download of compiled binaries is not for everyone:
http://xiaomi.eu/community/threads/android-4-3-for-mi2-2s-2a-open-source.22539/page-3#post-185235
and I do not have a framework setup for crosscompiling for android (never tried it, anyway).

**Comment by M1cha** [comment]
http://d-h.st/fAu

**Comment by ghost** [comment]
It works fine with Ivan's ROM (installed to System 2 with True Dual Boot and factory reset for that System via CWM), incl. switching the mic mute on/off during the call.

Do you need some other debug info or hint?

**Comment by M1cha** [comment]
no that's enough thx.

**Comment by M1cha** [comment]
should be fixed in 2013-11-27, pls confirm

**Comment by ghost** [comment]
Flashed 2013-11-27 in CWM, wiped Dalvik Cache and rebooted.

I can hear the other party during phone call, but the mic on headset is not used - instead the mic in phone seems to be used. (I checked recordings on both phones.) The button does not do anything during phone call (neither in Apollo player).

Sound recorder works fine with headset (though I have not tried it before the update), however the recording suffers from a perpetual cracking luckily-not-so-much-loud sound with a frequency of approximately 1.5 Hz.

Could a complete factory reset make a difference? (I am reluctant to do so, since then I would have to ask the banks for mobile banking re-activation and also my employer for re-approval for data synchronisation.)

**Comment by M1cha** [comment]
Wiping data wouldn't make any difference.
I'll take a look at the mic problem.

**Comment by ghost** [comment]
I have sacrificed the ROM on the other System in true dual boot. Interestingly, the mic on headset works during the phone call.

Crackling sound remains (it's like the sound of a turning propeller of a chopper, actually a bit faster than 1.5 Hz) and something causes the sound recorder to jump to a maximum sensitivity (crackling is very loud) quite often.

I will do some more tests tomorrow with my normal-use ROM (I use ACR call recorder, exDialer instead of the standard Phone app, XPrivacy, etc... - these could have some impact, possibly).

**Comment by Vosje** [comment]
Downloaded and installed version 20131127, headphone works like a charm now  Thanks for alle the work you're putting into this ROM
